name: MLGRush
version: 1.1
author: PrinxIsLeqit
api: 3.0.0
main: PrinxIsLeqit\MLGRush\MLGRush
description: 'MLGRush'
commands:
    mlgrush:
        description: 'MLGRush main command'
    leave:
        description: 'Leave command'
    hub:
        description: 'Hub command'
        aliases: [lobby, l]
